# -*- org-confirm-babel-evaluate: nil -*-
#+title: Modern Bayesian Tools for Time Series Analysis
#+author: Thomas P. Harte and R. Michael Weylandt
#+email: tharte@cantab.net
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./3331384/github.css" />
#+HTML_MATHJAX: align:"left" path:"https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
#+INFOJS_OPT: view:info toc:t
#+PROPERTY: session *R*
#+BIBLIOGRAPHY: /home/tharte/include/refs
#+BIBLIOGRAPHY_STYLE: /home/tharte/include/ths
#+OPTIONS: tex:t   # do the right thing automatically (MathJax)

* Disclaimer
** Please read the following Disclaimer carefully
#+BEGIN_QUOTE
    Thomas P. Harte and R. Michael Weylandt ("the Authors") are providing
    this presentation and its contents ("the Content") for educational
    purposes only at the /R in Finance Conference/, 2016-05-20,
    Chicago, IL.  Neither of the Authors is a registered investment advisor
    and neither purports to offer investment advice nor business advice.

    You may use any of the Content under the terms of the
    [[http://choosealicense.com/licenses/mit/][MIT License]] ([[sec:MIT_License][see below]]).

    The Content is provided for informational and educational purposes only
    and should not be construed as investment or business advice. Accordingly,
    you should not rely on the Content in making any investment or business
    decision.  Rather, you should use the Content only as a starting point
    for doing additional independent research in order to allow you to form
    your own opinion regarding investment or business decisions.  You are
    encouraged to seek independent advice from a competent professional
    person if you require legal, financial, tax or other expert assistance.

    The Content may contain factual or typographical errors: the Content
    should in no way be construed as a replacement for qualified, professional
    advice.  There is no guarantee that use of the Content will be profitable.
    Equally, there is no guarantee that use of the Content will not result
    in losses.

    THE AUTHORS SPECIFICALLY DISCLAIM ANY PERSONAL LIABILITY, LOSS OR RISK
    INCURRED AS A CONSEQUENCE OF THE USE AND APPLICATION, EITHER DIRECTLY
    OR INDIRECTLY, OF THE CONTENT. THE AUTHORS SPECIFICALLY DISCLAIM ANY
    REPRESENTATION, WHETHER EXPLICIT OR IMPLIED, THAT APPLYING THE CONTENT
    WILL LEAD TO SIMILAR RESULTS IN A BUSINESS SETTING. THE RESULTS PRESENTED
    IN THE CONTENT ARE NOT NECESSARILY TYPICAL AND SHOULD NOT DETERMINE
    EXPECTATIONS OF FINANCIAL OR BUSINESS RESULTS.
#+END_QUOTE

** MIT License
<<sec:MIT_License>>
#+BEGIN_QUOTE
    The [[http://choosealicense.com/licenses/mit/][MIT License]]:

    Copyright (c) 2016 Thomas P. Harte & R. Michael Weylandt
(see below).
    Permission is hereby granted, free of charge, to any person obtaining a
    copy of this software and associated documentation files (the "Software"),
    to deal in the Software without restriction, including without limitation
    the rights to use, copy, modify, merge, publish, distribute, sublicense,
    and/or sell copies of the Software, and to permit persons to whom the
    Software is furnished to do so, subject to the following conditions:

    The above copyright notice and this permission notice shall be included
    in all copies or substantial portions of the Software.

    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
    THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
    OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
    ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
    OTHER DEALINGS IN THE SOFTWARE.
#+END_QUOTE

* Seminar: Modern Bayesian Tools for Time Series Analysis
The talk was comprised of:
1. [[][Michael's talk]], and
1. [[./mbt.html][Thomas's talk]]

The source for [[./mbt.html][Thomas's talk]] is at the GitHub repo:
http://github.com/tharte/mbt. Specifically, you can build the talk
from the Org file =mbt.org= in the repo, either from Emacs by
exporting to HTML (=C-c C-e h h=) or by running =make= at the command
line.
